### ISSUE TITLE
Lint markdown and mdx files to make sure there are no broken links

### ISSUE THREAD

**Issue by r-marques** [keyko-io/nevermined-docs#85]
The docs website will fail to build if there are any broken links.

Projects should lint the markdown and mdx files with something like `remark-lint` and https://github.com/davidtheclark/remark-lint-no-dead-urls to check for dead urls and other problems

**Comment by aaitor** [comment]
I think docusaurus is doing this during the build phase:
https://github.com/nevermined-io/docs/actions/runs/3097877865/jobs/5015079214#step:5:29
